repos:
  - repo: local
    hooks:
      - id: swift-format
        name: swift-format
        language: system
        entry: swift-format format -i
        types: [swift]

      - id: swiftlint
        name: swiftlint
        language: system
        entry: swiftlint lint --config .swiftlint.yml
        types: [swift]
